spring.application.name=plataforma-educativa

# Oracle FreeSQL Connection (TCPS)
spring.datasource.url=jdbc:oracle:thin:@tcps://db.freesql.com:2484/23ai_mb9q7?javax.net.ssl.trustStore=/app/truststore.jks&javax.net.ssl.trustStoreType=JKS&javax.net.ssl.trustStorePassword=changeit
spring.datasource.username=SQL_RVW2CCZORM3S7JVNWEAP94L7BS
spring.datasource.password=YI6bBG3A8YSOI2J9SKCNAMF$95TXJ5
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=8080

# AWS S3 - via variables de entorno
aws.s3.access-key=${AWS_ACCESS_KEY_ID}
aws.s3.secret-key=${AWS_SECRET_ACCESS_KEY}
aws.s3.region=us-east-1
aws.s3.bucket-name=plataforma-educativa-duoc

# Directorio temporal
app.files.temp-dir=temp-files
